// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxfabfzvllifwkstekwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4ZmFiZnp2bGxpZndrc3Rla3dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5OTA3OTUsImV4cCI6MjA2NTU2Njc5NX0.uFVygegjZOaBcEU8WI4NtbAuL8vzLY7R6omcv6LuOG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);